<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:tns="http://xmlns.oracle.com/communications/sce/dictionary/Training_Access_Service/Training_Access_Service" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://xmlns.oracle.com/communications/sce/dictionary/Training_Access_Service/Training_Access_Service">
    <xs:simpleType name="mwType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="40"/>
    </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="peDeviceName">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="40"/>
    </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="pePort">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="40"/>
    </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="switchHostName">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="40"/>
    </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="swPort">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="40"/>
    </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="oltDeviceName">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="40"/>
    </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="oltPort">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="40"/>
    </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="mediaType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="40"/>
    </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="serviceAction">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="40"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
